spring:
  application:
    name: SRV-CONTA-CORRENTE
  datasource:
    url: jdbc:mysql://localhost:3306/operacoes_bancarias
    username: root
    password: 1234567
  jpa:
    hibernate:
      ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          show_sql: true

server:
  port: 8081
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      #defaultZone: http://eureka-server:8761/eureka
#logging:
#  pattern:
#    level: 5p [${spring.application.name},%X{traceId:-},%X(spanId:-}]
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
springdoc:
  api-docs:
    path: /v3/api-docs  # Caminho para a documentação OpenAPI
  swagger-ui:
    path: /swagger-ui.html  # Caminho para a interface do Swagger