springdoc:
  api-docs:
    path: /v3/api-docs  # Caminho para a documentação OpenAPI
  swagger-ui:
    path: /swagger-ui.html  # Caminho para a interface do Swagger


spring:
  application:
    name: SRV-ABERTURA-CONTA
server:
  port: 8087

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
#logging:
#  pattern:
#    level: '%5p [${spring.application.name},%X{traceId:-},%X(spanId:-}]'

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
     sampling:
       probability: 1.0

