server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
spring:
  application:
    name: API-GATEWAY

management:
  endpoints:
    web:
      exposure:
        include: metrics,health,prometheus
  endpoint:
    metrics:
      enabled: true

