springdoc:
  api-docs:
    path: /v3/api-docs  # Caminho para a documentação OpenAPI
  swagger-ui:
    path: /swagger-ui.html  # Caminho para a interface do Swagger

spring:
  application:
    name: SRV-CADASTRO-CLIENTE
  datasource:
    url: jdbc:mysql://10.98.104.199:3306/operacoes_bancarias
    username: root
    password: 1234567
  jpa:
    hibernate:
      ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          show_sql: true

server:
  port: 8082
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://10.101.118.113:8761/eureka
management:
  zipkin:
    tracing:
      endpoint: http://10.109.126.152:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

  endpoints:
    web:
      exposure:
        include: metrics,health,prometheus
  endpoint:
    metrics:
      enabled: true
