spring:
  datasource:
    url: jdbc:mysql://localhost:3306/operacoes_bancarias_teste
    username: root
    password: 1234567
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          show_sql: true

server:
  port: 8082
 
  