apiVersion: v1
kind: Service
metadata: 
  name: api-gateway-svc-port
spec:
  selector:
    tier: api-gateway
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 30002
    port: 8080                              