apiVersion: v1
kind: Service
metadata: 
  name: banco-agro-svc
spec:
  type: ClusterIP
  ports:
  - name: srv-abertura-conta 
    protocol: TCP
    port: 8087
    targetPort: 8087
  - name: srv-cadastro-cliente  
    protocol: TCP
    port: 8082
    targetPort: 8082
  - name: srv-conta-corrente
    protocol: TCP
    port: 8081
    targetPort: 8081
  selector:
    tier: api-banco-agro