apiVersion: v1
kind: Pod
metadata: 
  name: db-mysql-pod
  labels:
    tier: db-mysql
spec:
  containers:
  - image: mysql:8.1
    name: db-mysql-pod
    env:
    - name: "MYSQL_DATABASE"
      value: "operacoes_bancarias"
    - name: "MYSQL_ROOT_PASSWORD"
      value: "1234567"
    ports:
    - containerPort: 3306