apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.51.1
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: "srv-cadastro-cliente"
        metrics_path: "/actuator/prometheus"
        scrape_interval: 3s
        static_configs:
        - targets: ["10.101.16.130:8082"]
        
      - job_name: "srv-abertura-conta"
        metrics_path: "/actuator/prometheus"
        scrape_interval: 3s
        static_configs:
        - targets: ["10.109.211.242:8087"]

      - job_name: "srv-conta-corrente"
        metrics_path: "/actuator/prometheus"
        scrape_interval: 3s
        static_configs:
        - targets: ["10.103.28.58:8081"]

      - job_name: "api-gateway"
        metrics_path: "/actuator/prometheus"
        scrape_interval: 3s
        static_configs:
        - targets: ["10.102.114.146:8080"]
