apiVersion: v1
kind: Service
metadata: 
  name: srv-cadastro-cliente-svc-port
spec:
  selector:
    tier: srv-cadastro-cliente
  type: NodePort
  ports:
  - name: porta-externa
    protocol: TCP
    port: 8082
    nodePort: 30003                              