apiVersion: v1
kind: Service
metadata: 
  name: srv-abertura-conta-svc-port
spec:
  selector:
    tier: srv-abertura-conta
  type: NodePort
  ports:
  - name: porta-externa
    protocol: TCP
    port: 8087
    nodePort: 30007                              