apiVersion: v1
kind: Pod
metadata: 
  name: srv-abertura-conta-pod
  labels: 
    tier: srv-abertura-conta
spec:
  containers:
  - image: bancoagro/srv-abertura-conta:0.3
    name: srv-abertura-conta-pod
    ports:
    - containerPort: 8087
    env:
    - name: SPRING_PROFILES_ACTIVE
      value: PRD
